---
output: html_document
---
Title: Math StatHW1
Author: Mbuthia, Ian.
---
Document doesn't compile as-is; -1
Overall score: 12/18

**Instructions:** The entirety of this assignment must be submitted as an R Markdown file (.Rmd) on your GitHub repository.  Use the .Rmd note handout files and the R Markdown cheat sheet as guidelines.  You are encouraged to save this HW1.Rmd file and fill in the questions with your answers, then submit.  **I should be able to knit your .Rmd file and compile your code myself, so make sure you do some bug checks before submitting!** (I.e., knit the document yourself a couple times and search for errors.)

2 dice are rolled, one red and one white.  
Let $Y$ be the random variable that denotes the maximum value of the two rolls. 
We will use simulation to find the mean and variance of $Y$, and then verify that our simulated results match what we would expect theoretically.

**Theoretical section**

1. (3pts) Define the pmf, find $\mu = E(Y)$, $\sigma^2 = Var(Y)$, and $\sigma = SD(Y)$.  Show all your work.
y should be 1:6; it's the max of two rolls.  -2
y <- (2:12)
py <- c(1/36, 2/36, 3/36, 4/36, 5/36, 6/36, 5/36, 4/36, 3/36, 2/36, 1/36)
y*py
mu <- sum(y*py)
mu
EY2 <- sum(y^2*py)
EY2
VarY <- EY2-mu^2
VarY
SD <- sqrt(VarY)
SD

2. (2pts)  Use `ggplot()` to plot the pmf; see Handout 1 notes for an example.

dd <- data.frame(y=y,probs = py)
ggplot(aes(x=y,y=probs),data=dd) + geom_bar(stat='identity') + 
  ylab('P(Y=y)') + ggtitle('pmf of Y for 2 Dice Rolled')
  
3. (2pts)  Consider the random variable $Z=2Y+1$.  What is $E(Z)$ and $Var(Z)$?  Show all work. 
  $E(Z) = E(2Y + 1) = 1 + 2E(Y)$
  $=1 + 2(7)$
  $=15$
  
  $Var(Z) = Var(2Y + 1) = 1^2*Var(Y)$
  $=1*5.833333$
  $=5.833333$
  Should be 2^2*Var(Y); -1
  
**Simulation section**  

4. (2pts) Use `replicate()` to simulate the results of 1000 pairs of rolls.  These are 1000 realizations of the random variable $Y$. Save the 1000 realizations in an object called `many.Y`.

  one.Y <- function () {
    sample.space <- c(1:6)
    red.die <- sample(sample.space, 1, replace = TRUE)
    white.die <- sample(sample.space, 1, replace = TRUE)
    max.die <- max(red.die, white.die)   
    return(max.die)
}
  one.Y()
    set.seed(1738)
    many.Y <- replicate(1000,one.Y())
    View(many.Y)

5.  (2pts) Use `ggplot()` to create the empirical (i.e., observed) pmf of your simulation.  See Handout 1 for example R code.  How does it compare with your theoretical pmf?
df <- data.frame(x=as.factor(many.Y))
ggplot(aes(x=as.factor(many.Y)),data=df) + geom_bar(aes(y=(..count..)/(sum(..count..)))) +
  ylab('Observed proportion') + xlab('y') + ggtitle('Simulated pmf')
  
  #
  
6. (1pt)  What is the mean of the 1000 realizations?
  mean (many.Y)
  
7.(1pt)  What is the variance of the 1000 realizations?
  var(many.Y)
  
8.  (1pt) What is the standard deviation of the 1000 realizations?
  sd(many.Y)

9. (1pt)  Create a new object called `many.Z` that creates 1000 realizations of $Z$.
many.Z <- replicate(1000,one.Y())
    View(many.Z)
Z is not just more Y; it's 2*Y + 1.  -1
10. (1pt)  What is the mean of $Z$?
  mean(many.Z)
   
11. (1pt)  What is the variance of $Z$?
  var(many.Z)
  
12. (1pt) Note that your simulated results should be similar to the theoretical quantities; if they aren't, re-check your R code!  What is the reason for any differences?
  
???  -1



